### ISSUE TITLE
Loading a file deletes structures

### ISSUE THREAD

**Issue by sirkrypt0** [hpi-swa-teaching/RichTextEditing#133]
Loading a file deletes structures that have been added manually before loading the file.
Additionally after loading a file, new structures that are added in the *Manage structures* window are not shown in the editor.

Steps to reproduce:
1. Create a new structure
2. Load a file from disk
3. The structure from 1 will disappear
4. Create a new structure
5. The structure from 4 won't show in the editor

**Comment by frcroth** [comment]
Loading a file deleting existing structures is expected behavior, as a new document is created on import.

**Comment by sirkrypt0** [comment]
> Loading a file deleting existing structures is expected behavior, as a new document is created on import.

True

**Comment by frcroth** [comment]
Observation at step 5 might still be interesting

**Comment by sirkrypt0** [comment]
I opened a new issue for that, see #141
