### ISSUE TITLE
Saving a document via CTRL+S or Save disables new structures

### ISSUE THREAD

**Issue by sirkrypt0** [hpi-swa-teaching/RichTextEditing#136]
# Issue
When saving created text via CTRL+S or the Save menu item, it is not possible to create new text structures.

# Steps to reproduce:
1. Open a new editor
2. Enter some text
3. Hit CTRL+S or the Save menu item
4. Open the Manage Structures window
5. Create a new structure
    * Note that the new structure won't show up in the editor

# Expected behavior:
The newly created structures also shows up in the editor.

**Comment by frcroth** [comment]
Relates to #104 see @MrModder's comment there for a possible explanation on why this happens

**Comment by oleschl** [comment]
I have looked in to this and it turns out that the buffer document loses his dependents when saving. Therefore the document cannot not inform the model about structure changes. 
The buffer document loses his dependents because of bad use of copy.

**Comment by frcroth** [comment]
fixed with 4dd64724926a0574adfb4f8ef864283a8b17a475
