### ISSUE TITLE
Class naming scheme

### ISSUE THREAD

**Issue by sirkrypt0** [hpi-swa-teaching/RichTextEditing#139]
Using *RT* as a prefix instead of *RichText* allows for shorter and thus easier to read class names

**Comment by frcroth** [comment]
I'm fine with it either way

**Comment by j-hellenberg** [comment]
Not necessary imo. Furthermore, one might imagine it as beeing an inbuild Squeak App and not just a random project at some point, and RichText is much less ambigous than RT in this context. RT only makes sense as long as you know what it stands for.

**Comment by j-hellenberg** [comment]
Perhaps we should rename TextStructure, NullTextStructure and TextExtendability to indicate belonging to the project though

**Comment by frcroth** [comment]
> 
> 
> Perhaps we should rename TextStructure, NullTextStructure and TextExtendability to indicate belonging to the project though

Yes I think that's a good idea

**Comment by frcroth** [comment]
can be discussed next monday

**Comment by frcroth** [comment]
Customer says:
Short prefix would be the preffered Squeak way. Should be done as the last change, as it may destroy history.

**Comment by frcroth** [comment]
Change on Friday.
