### ISSUE TITLE
Importing a file does not allow creating new structures

### ISSUE THREAD

**Issue by sirkrypt0** [hpi-swa-teaching/RichTextEditing#141]
# Description
When loading a file via the **Import from file** button, newly created structures don’t show up in the editor.

# Steps to reproduce
1. Open a new editor.
2. Load text from a file via the **Import from file** button.
3. Create a new structure via the **Manage Structures** menu.
    * Note that the newly created structure does not show up in the editor.

# Expected behaviour
Structures that are created after importing from a file show up in the editor and can be applied to the text.

**Comment by j-hellenberg** [comment]
I am experiencing the same problem when trying to select a new template on a saved file, also some structures are not working one a loaded document. Maybe the dependents for the observer-pattern aren't properly updated?
