### ISSUE TITLE
Structure Editor does not show selected structure

### ISSUE THREAD

**Issue by sirkrypt0** [hpi-swa-teaching/RichTextEditing#144]
# Description
The structure editor does not indicate, which structure I am currently editing.

# Expected behavior
When clicking on a structure in the Structure Editor, the list item turns bold such that I can see, which structure I am editing right now.

**Comment by LeonMatthes** [comment]
This might actually be a problem specific to the SWT-image.
In my SWT-image, list views have a bug, that causes them to not show which item is selected. This also happens in the Git-Browser, etc.

Have you tried upgrading your image?

**Comment by oleschl** [comment]
Actually only a change message was missing
