### ISSUE TITLE
Add Morphic-Testing-Framework to dependencies

### ISSUE THREAD

**Issue by MartinBuessemeyer** [hpi-swa-teaching/RichTextEditing#17]
Add Morphic-Testing-Framework to dependencies to baseline and try if it is working with travis-ci.

**Comment by leonschmidt99** [comment]
Finally worked out how to include MTF in Travis (also manipulated our "classesWithLabel" constant to be able to use "findByLabel:" for our PluggableButtonMorphPlus')
