### ISSUE TITLE
Button to open the RichTextEditor

### ISSUE THREAD

**Issue by LeonMatthes** [hpi-swa-teaching/RichTextEditing#19]
As someone who wants to write structured text, I want to be able to open the editor via a button, in order to access the tool without having to write Smalltalk code.

Acceptance criteria:
- [x] A button in the Apps dropdown menu labeled 'Rich Text Editor' exists
- [x] clicking the button opens the Rich Text Editor

Estimated effort: 3

**Comment by leonschmidt99** [comment]
Done so far.
