### ISSUE TITLE
Paragraph formatting

### ISSUE THREAD

**Issue by LeonMatthes** [hpi-swa-teaching/RichTextEditing#25]
As a user who wants to structure his text into paragraphs, I would like to have a different text composition for paragraphs, in order to easily identify paragraphs and to not have to add an additional character for the carriage return.

Acceptance criteria:
- [x] The paragraph symbol is no longer visible
- [x] A newline is rendered at the end of each paragraph
- [x] The next paragraph is spaced further from the previous paragraph than a newline would be
- [x] It is not possible to remove the newline from the paragraph without removing the paragraph ending

**Comment by lauraholz** [comment]
Estimated effort: 3

**Comment by LeonMatthes** [comment]
New estimated effort: 3
