### ISSUE TITLE
PR33, while solving #25, broke Travis pretty heavily

### ISSUE THREAD

**Issue by leonschmidt99** [hpi-swa-teaching/RichTextEditing#35]
Travis now cannot execute tests because of
`MessageNotUnderstood: MetacelloBaselineConstructor>>postLoad:`
This needs to be fixed in order for Travis to work properly again.

**Comment by leonschmidt99** [comment]
This also prevents the project from being installed via Metacello (tested in Squeak 5.2)

**Comment by LeonMatthes** [comment]
My bad, the correct call is `postLoadDoIt:`, not `postLoad:`
