### ISSUE TITLE
Define extendability of text structures

### ISSUE THREAD

**Issue by LeonMatthes** [hpi-swa-teaching/RichTextEditing#36]
As a text writer, I want to be able to define which text structures should be extended when I type at the end of it and which should not.

**Acceptance criteria**
- [x] For any given text structure type I can define whether the text structure is extendable
- [x] If the text structure type is defined as non-extendable when I type at the end of a text structure, it should not span the newly typed characters

**Comment by leonschmidt99** [comment]
Estimated effort: 3
