### ISSUE TITLE
Text structure type templates

### ISSUE THREAD

**Issue by LeonMatthes** [hpi-swa-teaching/RichTextEditing#37]
As a text writer, I want to be able to have different templates for the available text structure types, in order to easier match the structure of my text to common formats (Markdown, Latex, HTML, etc.).

**Acceptance criteria:**
- [x] An option to select a template exists
- [x] There are several predefined templates (including at least Markdown)
  * The Markdown option contains at least the following types:
    * Heading 1-6
    * bold
    * italic
    * Code
    * List item levels 1 - 3
    * Enumerated list items level 1-3
    * Quotes
- [x] When the option is selected all available text structure types are switched for the ones available in the template

**Comment by leonschmidt99** [comment]
Estimated effort: 5

**Comment by frcroth** [comment]
8
