### ISSUE TITLE
Associate text structure types to Rich Text

### ISSUE THREAD

**Issue by LeonMatthes** [hpi-swa-teaching/RichTextEditing#38]
As a text writer, I want that my text structure types are no longer global, but saved with the rich text, in order to not have them accumulate over time.

**Acceptance criteria:**
- [x] When I create a new text structure type and create a new document, it is no longer available
- [x] When I create a new text structure type and save and reload the document, the type is available again.
- [x] The same goes for deleting text structure types

**Comment by leonschmidt99** [comment]
Estimated effort: 3
