### ISSUE TITLE
Save progress

### ISSUE THREAD

**Issue by lauraholz** [hpi-swa-teaching/RichTextEditing#4]
As someone who wants to write text, I want to be able to save and reopen my text at any given time, in order to be able to continue working on the text later on.

Acceptance criteria:
- [ ] save button
- [ ] user can choose a location on the computer
- [ ] open text button
- [ ] text files can be opened and shown

**Comment by leonschmidt99** [comment]
With #13 done, this seems deprecated considering #5 .
