### ISSUE TITLE
Custom font for text structure type

### ISSUE THREAD

**Issue by LeonMatthes** [hpi-swa-teaching/RichTextEditing#42]
As someone who wants to write structured text, I want to be able to set the font for any text structure type, in order to easier distinguish it from other text structure tyes

**Acceptance criteria:**
- [x] I can assign any of the existing fonts to any of the available text structure types
- [x] I can assign a font of a specific size to the text structure type
- [x] I can easily reset the font (size) to default

**Comment by leonschmidt99** [comment]
Estimated effort: 5
