### ISSUE TITLE
Add "New" button

### ISSUE THREAD

**Issue by leonschmidt99** [hpi-swa-teaching/RichTextEditing#46]
As someone who often writes new texts, I want to be able to create a new Text in the editor by clicking a button instead of having to start writing first and then "Save as...".

- [ ] "New" button exists
- [ ] when the button is clicked, a new, Rich Text Editor window is opened

**Comment by LeonMatthes** [comment]
Why not make this button just open a new window?

**Comment by LeonMatthes** [comment]
Estimated effort: 1
