### ISSUE TITLE
Text structure that is assigned in the middle of text is applied for further text

### ISSUE THREAD

**Issue by leonschmidt99** [hpi-swa-teaching/RichTextEditing#49]
As someone who wants to fluently write text and knows beforehand that a structure will be needed in the following part of the text, I want to be able to choose an extendable structure for the next text that I type when my cursor is at the end of the current text.

- [x] when the cursor selects a position and not a region of text and a structure is selected, the structure is applied to next text that is typed (if it is extendable)
- [x] when a structure is selected this way and the cursor is moved away the structure will not be applied to the next typed text

**Comment by LeonMatthes** [comment]
Estimated effort: 5
