### ISSUE TITLE
Shortcut support

### ISSUE THREAD

**Issue by j-hellenberg** [hpi-swa-teaching/RichTextEditing#61]
As an user with a preference for using the keyboard as much as possible, I want to be able to use shortcuts to assign structures in my text, in order to reduce the number of necessary mouse clicks and to increase my productivity.

(Note: This is a duplicate of issue #12, which was closed (most likely rejected back then) and I am unable to reopen it at this point).

**Acceptance criteria**:
- [x] The first ten structures are assigned a shortcut from Ctrl+1 to Ctrl+0 (0=10 in this case).
- [x] When hitting the shortcut in the Rich Text Editor, the same action is taken as if the corresponding structure was selected in the list of available structures
- [x] If the structures ordering is changed, the shortcuts update accordingly

Estimated effort: 8

**Comment by MrModder** [comment]
Estimated effort: 8
