### ISSUE TITLE
Bug: Changing the structure order doesn't update correctly

### ISSUE THREAD

**Issue by LeonMatthes** [hpi-swa-teaching/RichTextEditing#72]
### Bug description
Changing the structure ordering in the 'manage structures' window doesn't change the displayed order in the editor, even though internally it has actually changed

### How to reproduce
1. Open the 'Manage structures' tab.
2. Move a structure (i.e. bold) around.
3. Close the manage structures window
4. Click the moved item
Now instead of applying the moved structure, the structure that is now at that internal index is applied.

### Expected behavior
Either the structures list reflects the list in the 'Manage structures' window, or it still activates the correct structure, even though the indices changed.

**Comment by sirkrypt0** [comment]
I am certainly not able to reproduce this. Opening a fresh window and applying the listed steps does behave as expected.
