### ISSUE TITLE
Setup SmalltalkCI as Github Action

### ISSUE THREAD

**Issue by sirkrypt0** [hpi-swa-teaching/RichTextEditing#74]

**Comment by frcroth** [comment]
Also add new links in readme

**Comment by sirkrypt0** [comment]
And change the badge “build: passed” to match the GitHub action, as it shows the travis ci build right now (you can do this by changing the link to the image in the README file). 
Also make sure to set the target branch of the badge to the **dev** branch if there is such option. 
I know that the current “build passed” badge is fixed onto the master branch and does not show the correct state when switching to another branch.
