### ISSUE TITLE
Choose XP practices

### ISSUE THREAD

**Issue by sirkrypt0** [hpi-swa-teaching/RichTextEditing#75]
measure everything

**Comment by frcroth** [comment]
Sustainable Development
_Do not work more than one consecutive week of overtime._
_Sleep well and at least 7 hours per night_
_Teamspiele!_

**Comment by frcroth** [comment]
weekly stand-up meeting with progress and problems

**Comment by frcroth** [comment]
### Ressources Scopes Trends
Track and measure:
Resources: Developers, Time (should be constant), Quality (e.g. SWALint, Coverage)
detect trends -> act on these trends (decrease scope wehen quality is shrinking)
Build graphs!

**Comment by frcroth** [comment]
maybe **Acceptance Testing**
as used by previous developers

**Comment by sirkrypt0** [comment]
- Collective Codeownership
- Planning Game
- Ten Minute Build
- Coding Standards
- Small Releases

**Comment by frcroth** [comment]
Planning Poker
