### ISSUE TITLE
Save to file system

### ISSUE THREAD

**Issue by frcroth** [hpi-swa-teaching/RichTextEditing#87]
As a user, who writes texts in SquidWord, I want to save my written texts to my hard drive in order to send them to other people.
Sub story of #5 

Acceptance criteria:
- [x] There is an option to export into file system
- [x] When selected a dialog to select a location opens
- [x] A file is saved at that location when confirmed
- [x] The saved file contains the text of the current document

Estimated Effort: 5

**Comment by LeonMatthes** [comment]
Note: the option should be labeled 'export as file' instead of 'save to file'.

**Comment by frcroth** [comment]
It would be nice if you already added a menu where you can choose in which format you want to export. This way you can add options for serialization and markdown later.

**Comment by frcroth** [comment]
Please also add a new category `import and export` in the model class and possibly rename loading methods to import
