### ISSUE TITLE
Paragraphs

### ISSUE THREAD

**Issue by lauraholz** [hpi-swa-teaching/RichTextEditing#9]
As someone who wants to write longer texts, I want to be able to have several paragraphs in my text, in order to structure it.

Acceptance criteria:

- [x] create new paragraphs by pressing 'Enter'
- [x] Do not create a new paragraph when pressing Shift+'Enter', but create a new line
- [x] Where a paragraph is in the text, a paragraph symbol is displayed
- [x] When I enter a new paragraph, a newline is added behind the paragraph symbol
- [x] The paragraph symbol is displayed between two paragraphs, not at the end of each

Estimated effort: 13 See #20

**Comment by LeonMatthes** [comment]
Possibly split into two issues: research + implementation

**Comment by LeonMatthes** [comment]
New estimate: 8
